package dmapp

var m = []Monster{
	Monster{
		MonsterID:       "Monster0",
		Name:            "Fledgling White Dragon",
		Level:           1,
		Role:            "Solo Brute",
		Size:            "Large",
		Origin:          "Natural Magical",
		Type:            "Beast (Dragon)",
		XP:              500,
		Health:          128,
		BloodiedHealth:  64,
		InitiativeBonus: 0,
		ArmorClass:      15,
		Fortitude:       15,
		Reflex:          11,
		Will:            13,
		Senses:          []string{"Darkvision"},
		Speed:           "6 (ice walk), fly 6",
		Resist:          []string{"5 cold"},
		SavingThrows:    5,
		ActionPoints:    2,
		Traits: []Trait{
			Trait{
				Name:   "Savage Blood",
				Effect: "While the dragon is bloodied, it can score a critical hot on a roll of 17-20.",
			},
		},
		StandardActions: []StandardAction{
			StandardAction{
				Name:     "Bite",
				Keywords: []string{"cold"},
				Usage:    "At-Will",
				Attacks: []Attack{
					Attack{
						Range:       "Melee 2",
						Targets:     "one creature",
						AttackBonus: 6,
						Versus:      "AC",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    1,
						DieSides:    12,
						DamageBonus: 11,
						HitInfo:     "Cold damage",
					},
				},
			},
			StandardAction{
				Name:  "Claws",
				Usage: "At-Will",
				Attacks: []Attack{
					Attack{
						Range:       "Melee 2",
						Targets:     "one or two creatures",
						AttackBonus: 6,
						Versus:      "AC",
						AttackInfo:  "If the dragon targets only one creature, it can make this attack twice against that creature.",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    1,
						DieSides:    12,
						DamageBonus: 4,
						HitInfo:     "damage",
					},
				},
			},
			StandardAction{
				Name:        "Breath Weapon",
				Keywords:    []string{"cold"},
				Usage:       "Recharge",
				Recharge:    []int{5, 6},
				Uses:        1,
				CurrentUses: 1,
				UsesPer:     "recharge",
				Attacks: []Attack{
					Attack{
						Range:       "Close blast 5",
						Targets:     "creatures in the blast",
						AttackBonus: 4,
						Versus:      "Reflex",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    2,
						DieSides:    8,
						DamageBonus: 4,
						HitInfo:     "cold damage, and the target is slowed (save ends).",
					},
				},
				Miss: "Half Damage",
			},
		},
		TriggeredActions: []TriggeredAction{
			TriggeredAction{
				Name:     "Tail Slap",
				Usage:    "At-Will",
				Trigger:  "An enemy hits the dragon while flanking it.",
				Reaction: "Immediate Reaction",
				Attacks: []Attack{
					Attack{
						Range:       "Melee 2",
						Targets:     "triggering enemy",
						AttackBonus: 4,
						Versus:      "Fortitude",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    1,
						DieSides:    12,
						DamageBonus: 4,
						HitInfo:     "damage, and the dragon pushes the target up to 3 squares.",
					},
				},
			},
			TriggeredAction{
				Name:    "Bloodied Breath",
				Usage:   "Encounter",
				Trigger: "The dragon is first bloodied.",
				Effect:  "(Free Action) Breath weapon recharges, and the dragon uses it.",
			},
		},
		Athletics:       9,
		Perception:      7,
		Strength:        18,
		StrengthMod:     4,
		Constitution:    16,
		ConstitutionMod: 3,
		Dexterity:       11,
		DexterityMod:    0,
		Intelligence:    8,
		IntelligenceMod: -1,
		Wisdom:          15,
		WisdomMod:       2,
		Charisma:        8,
		CharismaMod:     -1,
		Alignment:       "evil",
		Languages:       []string{"Common", "Draconic"},
	},
	Monster{
		MonsterID:       "Monster1",
		Name:            "Goblin Cutthroat",
		Level:           1,
		Role:            "Skirmisher",
		Size:            "Small",
		Origin:          "natural",
		Type:            "humanoid",
		XP:              100,
		Health:          30,
		CurrentHealth:   30,
		TemporaryHealth: 0,
		BloodiedHealth:  15,
		InitiativeBonus: 5,
		ArmorClass:      15,
		Fortitude:       13,
		Reflex:          14,
		Will:            13,
		Senses:          []string{"Low-light Vision"},
		Speed:           "6",
		StandardActions: []StandardAction{
			StandardAction{
				Name:     "Short Sword",
				Keywords: []string{"weapon"},
				Usage:    "At-Will",
				Attacks: []Attack{
					Attack{
						Range:       "Melee 1",
						Targets:     "one creature",
						AttackBonus: 6,
						Versus:      "AC",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    1,
						DieSides:    6,
						DamageBonus: 5,
						HitInfo:     "damage, and the goblin shifts 1 square.",
					},
					Hit{
						DieCount:    2,
						DieSides:    6,
						DamageBonus: 5,
						HitInfo:     "damage, if the goblin has combat advantage against the target, and the goblin shifts 1 square.",
					},
				},
			},
			StandardAction{
				Name:        "Dagger",
				Keywords:    []string{"weapon"},
				Usage:       "At-Will",
				Uses:        2,
				CurrentUses: 2,
				UsesPer:     "encounter",
				Attacks: []Attack{
					Attack{
						Range:       "Ranged 5/10",
						Targets:     "one creature",
						AttackBonus: 6,
						Versus:      "AC",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    1,
						DieSides:    4,
						DamageBonus: 5,
						HitInfo:     "damage.",
					},
				},
			},
		},
		MoveActions: []MoveAction{
			MoveAction{
				Name:   "Deft Scurry",
				Effect: "The goblin shifts 3 squares.",
			},
		},
		TriggeredActions: []TriggeredAction{
			TriggeredAction{
				Name:     "Goblin Tactics",
				Usage:    "At-Will",
				Trigger:  "The goblin is missed by a melee attack.",
				Reaction: "Immediate Reaction",
				Effect:   "The goblin shifts 1 square.",
			},
		},
		Perception:      2,
		Stealth:         8,
		Thievery:        8,
		Strength:        13,
		StrengthMod:     1,
		Constitution:    14,
		ConstitutionMod: 2,
		Dexterity:       17,
		DexterityMod:    3,
		Intelligence:    8,
		IntelligenceMod: -1,
		Wisdom:          14,
		WisdomMod:       2,
		Charisma:        8,
		CharismaMod:     -1,
		Alignment:       "evil",
		Languages:       []string{"Common", "Goblin"},
		Equipment:       []string{"leather armor", "light shield", "short sword", "2 daggers"},
	},
	Monster{
		MonsterID:       "Monster2",
		Name:            "Guard Drake",
		Level:           2,
		Role:            "Brute",
		Size:            "Small",
		Origin:          "natural",
		Type:            "beast (reptile)",
		XP:              125,
		Health:          48,
		CurrentHealth:   48,
		BloodiedHealth:  24,
		InitiativeBonus: 5,
		ArmorClass:      15,
		Fortitude:       15,
		Reflex:          13,
		Will:            12,
		Speed:           "6",
		StandardActions: []StandardAction{
			StandardAction{
				Name:  "Bite",
				Usage: "At-Will",
				Attacks: []Attack{
					Attack{
						Range:       "Melee 1",
						Targets:     "one creature",
						AttackBonus: 7,
						Versus:      "AC",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    1,
						DieSides:    10,
						DamageBonus: 5,
						HitInfo:     "damage.",
					},
					Hit{
						DieCount:    1,
						DieSides:    10,
						DamageBonus: 10,
						HitInfo:     "damage, while within 2 squares of an ally.",
					},
				},
			},
		},
		Perception:      7,
		Strength:        16,
		StrengthMod:     4,
		Constitution:    18,
		ConstitutionMod: 5,
		Dexterity:       15,
		DexterityMod:    3,
		Intelligence:    3,
		IntelligenceMod: -3,
		Wisdom:          12,
		WisdomMod:       2,
		Charisma:        12,
		CharismaMod:     2,
		Alignment:       "Unaligned",
		Languages:       []string{"--"},
	},
	Monster{
		MonsterID:       "Monster3",
		Name:            "Dracolich Servant",
		Level:           6,
		Role:            "Solo Controller",
		Size:            "Large",
		Origin:          "natural magical",
		Type:            "beast (dragon, undead)",
		XP:              1250,
		Health:          296,
		CurrentHealth:   296,
		TemporaryHealth: 0,
		BloodiedHealth:  148,
		InitiativeBonus: 10,
		ArmorClass:      20,
		Fortitude:       20,
		Reflex:          17,
		Will:            18,
		Senses:          []string{"Darkvision"},
		Speed:           "6, fly 8 (clumsy)",
		Immune:          []string{"disease", "poison"},
		Resist:          []string{"10 necrotic"},
		Vulnerable:      []string{"10 radiant"},
		SavingThrows:    5,
		ActionPoints:    2,
		Traits: []Trait{
			Trait{
				Name:   "Action Recovery",
				Effect: "Whenever the dragon ends its turn, any dazing, stunning, or dominating effect on it ends.",
			},
			Trait{
				Name:   "Instictive Domination",
				Effect: "On an initiative of 10 + its initiative check, the dragon can use a free action to use mesmerizing glance. This attack does not provoke opportunity attacks. If the dragon cannot use a free action to make this attack due to a dominationg or stunning effect, the that effect ends instead of the dragon making the attack.",
			},
		},
		StandardActions: []StandardAction{
			StandardAction{
				Name:     "Bite",
				Keywords: []string{"necrotic"},
				Usage:    "At-Will",
				Attacks: []Attack{
					Attack{
						Range:       "Melee 2",
						Targets:     "one creature",
						AttackBonus: 11,
						Versus:      "AC",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    4,
						DieSides:    6,
						DamageBonus: 5,
						HitInfo:     "damage, and ongoing 5 necrotic damage (save ends).",
					},
				},
			},
			StandardAction{
				Name:  "Claws",
				Usage: "At-Will",
				Attacks: []Attack{
					Attack{
						Range:       "Melee 2",
						Targets:     "one or two creatures",
						AttackBonus: 11,
						Versus:      "AC",
						AttackInfo:  "If the dragon targets only one creature, it can make this attack twice against that creature.",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    2,
						DieSides:    6,
						DamageBonus: 6,
						HitInfo:     "damage.",
					},
				},
				Effect: "The dracolish slides the target up to 2 squares.",
			},
			StandardAction{
				Name:        "Breath weapon",
				Keywords:    []string{"necrotic"},
				Recharge:    []int{5, 6},
				Uses:        1,
				CurrentUses: 1,
				Attacks: []Attack{
					Attack{
						Range:       "Close Blast 5",
						Targets:     "enemies in the blast",
						AttackBonus: 11,
						Versus:      "Reflex",
					},
				},
				Hits: []Hit{
					Hit{
						DieCount:    3,
						DieSides:    8,
						DamageBonus: 8,
						HitInfo:     "necrotic damage, and the target is weakened (save ends).",
					},
				},
				Miss: "Half damage, and the target is weakened until the end of its next turn.",
			},
		},
		MinorActions: []MinorAction{
			MinorAction{
				Name:        "Mesmerizing Glance",
				Keywords:    []string{"charm", "psychic"},
				Usage:       "At-Will",
				Uses:        1,
				CurrentUses: 1,
				UsesPer:     "round",
				Attacks: []Attack{
					Attack{
						Range:       "Ranged 10",
						Targets:     "one creature",
						AttackBonus: 11,
						Versus:      "Will",
					},
				},
				Hits: []Hit{
					Hit{
						HitInfo: "The target is dominated (save ends).",
					},
				},
				Miss:   "If the target willingly moves to a square nearer to or adjacent to the dracolish before the end of its next turn, it takes 15 psychic damage.",
				Effect: "The dracolich slides the target up to 2 squares.",
			},
		},
		TriggeredActions: []TriggeredAction{
			TriggeredAction{
				Name:    "Bloodied Breath",
				Trigger: "The dragon is first bloodied.",
				Effect:  "(Free Action) Breath Weapon recharges, and the dragon uses it.",
			},
		},
		Insight:         14,
		Perception:      14,
		Strength:        22,
		StrengthMod:     12,
		Constitution:    19,
		ConstitutionMod: 10,
		Dexterity:       19,
		DexterityMod:    10,
		Intelligence:    17,
		IntelligenceMod: 9,
		Wisdom:          17,
		WisdomMod:       9,
		Charisma:        18,
		CharismaMod:     10,
		Alignment:       "evil",
		Languages:       []string{"Common", "Draconic"},
	},
}
